using MindSculptor.DataAccess.Modelled.Records;
using MindSculptor.DataAccess.Modelled.Records.Fields;
using MindSculptor.DataAccess.Modelled.Records.Keys;
using MindSculptor.DataAccess.Modelled.Schemas;

namespace MindSculptor.App.AppDataModel.Schemas.Accounts.Tables
{
    public class Accounts : RecordDefinition
    {
        public override Schema Schema => MindSculptorDataModel.Accounts;


        public static IdField Id = new IdField.Definition 
        {
            IsAutoGenerated = true,
            IsReadOnly = true
        };

        public static TextField EmailAddress = new TextField.Definition
        {
            MinimumLength = 1,
            MaximumLength = 99
        };

        public static PrimaryKey PK = new PrimaryKey.Definition
        {
            Fields = Id
        };

        public static UniqueKey UQ = new UniqueKey.Definition
        {
            Fields = EmailAddress
        };
    }
}
