using MindSculptor.DataAccess.Modelled.Records;
using MindSculptor.DataAccess.Modelled.Records.Fields;
using MindSculptor.DataAccess.Modelled.Records.Keys;
using MindSculptor.DataAccess.Modelled.Schemas;

namespace MindSculptor.App.AppDataModel.Schemas.Cards.Tables
{
    public class Bases : RecordDefinition
    {
        public override Schema Schema => MindSculptorDataModel.Cards;


        public static readonly IdField Id = new IdField.Definition
        {
            IsAutoGenerated = true,
            IsReadOnly = true
        };

        public static readonly IdField CardTypeId = new IdField.Definition
        {
            MappedField = CardTypes.Id,
            IsReadOnly = true
        };

        public static readonly PrimaryKey PK = new PrimaryKey.Definition
        {
            Fields = Id
        };

        public static readonly ForeignKey FK = new ForeignKey.Definition
        {
            Fields = CardTypeId,
            ReferencedKey = CardTypes.PK
        };
    }
}
