using MindSculptor.DataAccess.Modelled.Records;
using MindSculptor.DataAccess.Modelled.Records.Fields;
using MindSculptor.DataAccess.Modelled.Records.Keys;
using MindSculptor.DataAccess.Modelled.Schemas;

namespace MindSculptor.App.AppDataModel.Schemas.Cards.Tables
{
    public class FacePrintings : RecordDefinition
    {
        public override Schema Schema => MindSculptorDataModel.Cards;


        public static IdField Id = new IdField.Definition
        {
            IsAutoGenerated = true,
            IsReadOnly = true
        };

        public static IdField BasePrintingId = new IdField.Definition
        {
            MappedField = BasePrintings.Id,
            IsReadOnly = true
        };

        public static IdField FaceId = new IdField.Definition
        {
            MappedField = Faces.Id,
            IsReadOnly = true
        };

        public static IdField ImageId = new IdField.Definition
        {
            IsAutoGenerated = true,
            IsReadOnly = false
        };

        public static PrimaryKey PK = new PrimaryKey.Definition
        {
            Fields = Id
        };

        public static UniqueKey UQ1 = new UniqueKey.Definition
        {
            Fields = FieldReference.List(BasePrintingId, FaceId)
        };

        public static UniqueKey UQ2 = new UniqueKey.Definition
        {
            Fields = ImageId
        };

        public static ForeignKey FK1 = new ForeignKey.Definition
        {
            Fields = BasePrintingId,
            ReferencedKey = BasePrintings.PK
        };

        public static ForeignKey FK2 = new ForeignKey.Definition
        {
            Fields = FaceId,
            ReferencedKey = Faces.PK
        };
    }
}
