using MindSculptor.DataAccess.Modelled.Records;
using MindSculptor.DataAccess.Modelled.Records.Fields;
using MindSculptor.DataAccess.Modelled.Records.Keys;
using MindSculptor.DataAccess.Modelled.Schemas;

namespace MindSculptor.App.AppDataModel.Schemas.Cards.Tables
{
    public class ManaSymbols : RecordDefinition
    {
        public override Schema Schema => MindSculptorDataModel.Cards;


        public static readonly IdField Id = new IdField.Definition
        {
            IsAutoGenerated = true,
            IsReadOnly = true
        };

        public static readonly TextField Type = new TextField.Definition
        {
            MinimumLength = 1,
            MaximumLength = 20,
            IsReadOnly = true
        };

        public static readonly TextField Code = new TextField.Definition
        {
            MinimumLength = 1,
            MaximumLength = 5,
            IsReadOnly = true
        };

        public static readonly IntegerField ConvertedManaCost = new IntegerField.Definition
        {
            MinimumValue = 0,
            MaximumValue = 15,
            IsReadOnly = true
        };

        public static readonly BooleanField HasWhiteIdentity = new BooleanField.Definition { IsReadOnly = true };

        public static readonly BooleanField HasBlueIdentity = new BooleanField.Definition { IsReadOnly = true };

        public static readonly BooleanField HasBlackIdentity = new BooleanField.Definition { IsReadOnly = true };

        public static readonly BooleanField HasRedIdentity = new BooleanField.Definition { IsReadOnly = true };

        public static readonly BooleanField HasGreenIdentity = new BooleanField.Definition { IsReadOnly = true };

        public static readonly BooleanField HasColorlessIdentity = new BooleanField.Definition { IsReadOnly = true };

        public static PrimaryKey PK = new PrimaryKey.Definition
        {
            Fields = Id
        };

        public static UniqueKey UQ1 = new UniqueKey.Definition
        {
            Fields = Type
        };

        public static UniqueKey UQ2 = new UniqueKey.Definition
        {
            Fields = Code
        };
    }
}
