using MindSculptor.DataAccess.Modelled.Records;
using MindSculptor.DataAccess.Modelled.Records.Fields;
using MindSculptor.DataAccess.Modelled.Records.Keys;
using MindSculptor.DataAccess.Modelled.Schemas;

namespace MindSculptor.App.AppDataModel.Schemas.Mtga.Tables
{
    public class DraftPicks : RecordDefinition
    {
        public override Schema Schema => MindSculptorDataModel.Mtga;


        public static readonly IdField Id = new IdField.Definition
        {
            IsAutoGenerated = true,
            IsReadOnly = true
        };

        public static readonly IdField DraftEventEntryId = new IdField.Definition
        {
            MappedField = DraftEventEntries.Id,
            IsReadOnly = true
        };

        public static readonly IdField DigitalCardId = new IdField.Definition
        {
            MappedField = Cards.Id,
            IsReadOnly = true
        };

        public static readonly IntegerField PackNumber = new IntegerField.Definition
        {
            MinimumValue = 1,
            MaximumValue = 3,
            IsReadOnly = true
        };

        public static readonly IntegerField PickNumber = new IntegerField.Definition
        {
            MinimumValue = 1,
            MaximumValue = 14,
            IsReadOnly = true
        };

        public static readonly IntegerField Ordinal = new IntegerField.Definition
        {
            MinimumValue = 0,
            MaximumValue = 13,
            IsReadOnly = true
        };

        public static readonly BooleanField IsPick = new BooleanField.Definition
        {
            IsReadOnly = true
        };

        public static PrimaryKey PK = new PrimaryKey.Definition
        {
            Fields = Id
        };

        public static UniqueKey UQ = new UniqueKey.Definition
        {
            Fields = FieldReference.List(DraftEventEntryId, PackNumber, PickNumber, Ordinal)
        };

        public static ForeignKey FK1 = new ForeignKey.Definition
        {
            Fields = DraftEventEntryId,
            ReferencedKey = DraftEventEntries.PK
        };

        public static ForeignKey FK2 = new ForeignKey.Definition
        {
            Fields = DigitalCardId,
            ReferencedKey = Cards.PK
        };
    }
}
