using MindSculptor.DataAccess.Modelled.Records;
using MindSculptor.DataAccess.Modelled.Records.Fields;
using MindSculptor.DataAccess.Modelled.Records.Keys;
using MindSculptor.DataAccess.Modelled.Schemas;

namespace MindSculptor.App.AppDataModel.Schemas.Mtga.Tables
{
    public class DraftPickOptions : RecordDefinition
    {
        public override Schema Schema => MindSculptorDataModel.Mtga;


        public static readonly IdField Id = new IdField.Definition
        {
            IsAutoGenerated = true,
            IsReadOnly = true
        };

        public static readonly IdField EventId = new IdField.Definition
        {
            MappedField = DraftEvents.EventId,
            IsReadOnly = true
        };

        public static readonly IdField EventEntryId = new IdField.Definition
        {
            MappedField = EventEntries.Id,
            IsReadOnly = true
        };

        public static readonly IdField DigitalCardId = new IdField.Definition
        {
            MappedField = DigitalCards.Id,
            IsReadOnly = true
        };

        public static readonly IntegerField PackNumber = new IntegerField.Definition
        {
            MinimumValue = 1,
            MaximumValue = 3,
            IsReadOnly = true
        };

        public static readonly IntegerField PickNumber = new IntegerField.Definition
        {
            MinimumValue = 1,
            MaximumValue = 15,
            IsReadOnly = true
        };

        public static readonly IntegerField Ordinal = new IntegerField.Definition
        {
            MinimumValue = 0,
            MaximumValue = 13,
            IsReadOnly = true
        };

        public static PrimaryKey PK = new PrimaryKey.Definition
        {
            Fields = Id
        };

        public static UniqueKey UQ = new UniqueKey.Definition
        {
            Fields = FieldReference.List(EventEntryId, PackNumber, PickNumber, Ordinal)
        };

        public static ForeignKey FK1 = new ForeignKey.Definition
        {
            Fields = EventId,
            ReferencedKey = DraftEvents.PK
        };

        public static ForeignKey FK2 = new ForeignKey.Definition
        {
            Fields = EventEntryId,
            ReferencedKey = EventEntries.PK
        };

        public static ForeignKey FK3 = new ForeignKey.Definition
        {
            Fields = DigitalCardId,
            ReferencedKey = DigitalCards.PK
        };
    }
}
