using MindSculptor.DataAccess.Modelled.Records;
using MindSculptor.DataAccess.Modelled.Records.Fields;
using MindSculptor.DataAccess.Modelled.Records.Keys;
using MindSculptor.DataAccess.Modelled.Schemas;

namespace MindSculptor.App.AppDataModel.Schemas.Mtga.Tables
{
    public class DraftEvents : RecordDefinition
    {
        public override Schema Schema => MindSculptorDataModel.Mtga;


        public static IdField Id = new IdField.Definition
        {
            IsAutoGenerated = true,
            IsReadOnly = true
        };

        public static IdField SetId = new IdField.Definition
        {
            MappedField = Schemas.Cards.Tables.Sets.Id,
            IsReadOnly = true
        };

        public static TextField DraftType = new TextField.Definition
        {
            MinimumLength = 1,
            MaximumLength = 20,
            IsReadOnly = true
        };

        public static PrimaryKey PK = new PrimaryKey.Definition
        {
            Fields = Id
        };

        public static UniqueKey UQ = new UniqueKey.Definition
        {
            Fields = FieldReference.List(SetId, DraftType)
        };

        public static ForeignKey FK = new ForeignKey.Definition
        {
            Fields = SetId,
            ReferencedKey = Schemas.Cards.Tables.Sets.PK
        };
    }
}
