using MindSculptor.DataAccess.Modelled.Records;
using MindSculptor.DataAccess.Modelled.Records.Fields;
using MindSculptor.DataAccess.Modelled.Records.Keys;
using MindSculptor.DataAccess.Modelled.Schemas;

namespace MindSculptor.App.AppDataModel.Schemas.Mtga.Tables
{
    public class Players : RecordDefinition
    {
        public override Schema Schema => MindSculptorDataModel.Mtga;


        public static IdField Id = new IdField.Definition
        {
            IsAutoGenerated = true,
            IsReadOnly = true
        };

        public static TextField MtgaUserId = new TextField.Definition
        {
            MinimumLength = 16,
            MaximumLength = 32,
            IsReadOnly = true
        };

        public static TextField Name = new TextField.Definition
        {
            MinimumLength = 1,
            MaximumLength = 40,
            IsReadOnly = true
        };

        public static IntegerField NameId = new IntegerField.Definition
        {
            MinimumValue = 1,
            MaximumValue = 999_999,
            IsReadOnly = true
        };

        public static PrimaryKey PK = new PrimaryKey.Definition
        {
            Fields = Id
        };

        public static UniqueKey UQ1 = new UniqueKey.Definition
        {
            Fields = MtgaUserId
        };

        public static UniqueKey UQ2 = new UniqueKey.Definition
        {
            Fields = FieldReference.List(Name, NameId)
        };
    }
}
