using System;

namespace MindSculptor.DataAccess.Modelled.Records.Fields
{
    public class IdField : Field<IdField>
    {
        public bool IsAutoGenerated { get; }

        private IdField(Definition definition)
            : base(definition)
        {
            IsAutoGenerated = definition.IsAutoGenerated;
        }

        public static implicit operator IdField(Definition definition)
            => new IdField(definition);

        protected override Type GetMappedDalType() 
            => typeof(Guid);

        public new class Definition : Field<IdField>.Definition
        {
            public bool IsAutoGenerated { get; set; } = false;
        }
    }
}
